version: "3"
services:
  app:
    build: .
    ports:
      - "8082:8080"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: bestuser
      DATABASE_PASSWORD: bestuser
      DATABASE_NAME: my_db
      DATABASE_PORT: 3306
    depends_on:
      - mysql
  mysql:
    image: "mysql:8.0"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: bestuser
      MYSQL_DATABASE: my_db
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: bestuser
volumes:
  mysql_data:


