# configuration
name: push

on:
  push:
    branches:
      -'*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      uses - analog plugin in action
      - name: put code from repo to VM
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
#        with - is settings
        with:
          java-version: 17
      - name: Hello world
        run: |
          echo 'Hello World'
          echo 'Hello World 2 '
          pwd
          ls -l
          mvn -version
      - name: Maven Package
        run: mvn clean install



